import os
import uuid
from pathlib import Path
from docx import Document
from openpyxl import Workbook
from pptx import Presentation
from app.core.config import settings
from app.tools.registry import register_tool

OUTPUT_DIR = Path(settings.output_dir).resolve()
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

@register_tool("generate_word_document")
def generate_word_document(title: str, content: str, author: str = "Kavach AI") -> str:
    """Generate a formatted Word document (.docx).
    
    Args:
        title: Title of the document.
        content: The main body text of the document.
        author: Author of the document.
    """
    doc = Document()
    doc.add_heading(title, 0)
    
    doc.add_paragraph(f"Author: {author}")
    doc.add_paragraph(content)
    
    filename = f"{uuid.uuid4().hex[:8]}_{title.replace(' ', '_')}.docx"
    filepath = OUTPUT_DIR / filename
    
    try:
        doc.save(filepath)
        return f"Successfully generated Word document: {filename}"
    except Exception as e:
        return f"Error generating document: {str(e)}"

@register_tool("generate_excel_sheet")
def generate_excel_sheet(title: str, headers: list, rows: list) -> str:
    """Generate an Excel spreadsheet (.xlsx).
    
    Args:
        title: Title of the sheet.
        headers: A list of column headers.
        rows: A list of rows, where each row is a list of cell values.
    """
    wb = Workbook()
    ws = wb.active
    ws.title = title[:31]  # Excel titles max 31 chars
    
    ws.append(headers)
    for row in rows:
        ws.append(row)
        
    filename = f"{uuid.uuid4().hex[:8]}_{title.replace(' ', '_')}.xlsx"
    filepath = OUTPUT_DIR / filename
    
    try:
        wb.save(filepath)
        return f"Successfully generated Excel spreadsheet: {filename}"
    except Exception as e:
        return f"Error generating spreadsheet: {str(e)}"

@register_tool("generate_presentation")
def generate_presentation(title: str, slides_content: list) -> str:
    """Generate a PowerPoint presentation (.pptx).
    
    Args:
        title: Main title of the presentation.
        slides_content: A list of dictionaries containing 'title' and 'content' for each slide.
    """
    prs = Presentation()
    
    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title_shape = slide.shapes.title
    subtitle = slide.placeholders[1]
    title_shape.text = title
    subtitle.text = "Generated by Kavach AI"
    
    # Content slides
    bullet_slide_layout = prs.slide_layouts[1]
    for slide_data in slides_content:
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        title_shape = shapes.title
        body_shape = shapes.placeholders[1]
        
        title_shape.text = slide_data.get("title", "")
        tf = body_shape.text_frame
        tf.text = slide_data.get("content", "")
        
    filename = f"{uuid.uuid4().hex[:8]}_{title.replace(' ', '_')}.pptx"
    filepath = OUTPUT_DIR / filename
    
    try:
        prs.save(filepath)
        return f"Successfully generated PowerPoint presentation: {filename}"
    except Exception as e:
        return f"Error generating presentation: {str(e)}"
