import re
import uuid

from docx import Document
from openpyxl import Workbook
from pptx import Presentation

from app.core.paths import OUTPUT_DIR
from app.tools.registry import register_tool


def _save(suffix: str, title: str) -> dict:
    """Build output path with UUID prefix and return metadata."""
    file_id = str(uuid.uuid4())
    safe_title = re.sub(r"[^A-Za-z0-9._-]+", "_", title).strip("._-")[:100] or "untitled"
    filename = f"{file_id}_{safe_title}.{suffix}"
    return {"file_id": file_id, "filename": filename, "path": OUTPUT_DIR / filename}


@register_tool("generate_word_document")
def generate_word_document(title: str, content: str, author: str = "Kavach AI") -> dict:
    """Generate a formatted Word document (.docx).

    Args:
        title: Title of the document.
        content: The main body text of the document.
        author: Author of the document.
    """
    try:
        meta = _save("docx", title)
        doc = Document()
        doc.add_heading(title, 0)
        doc.add_paragraph(f"Author: {author}")
        doc.add_paragraph(content)
        doc.save(meta["path"])
        meta["status"] = "ok"
        return meta
    except Exception as e:
        return {"status": "error", "error": str(e)}


@register_tool("generate_excel_sheet")
def generate_excel_sheet(title: str, headers: list, rows: list) -> dict:
    """Generate an Excel spreadsheet (.xlsx).

    Args:
        title: Title of the sheet.
        headers: A list of column headers.
        rows: A list of rows, where each row is a list of cell values.
    """
    try:
        meta = _save("xlsx", title)
        wb = Workbook()
        ws = wb.active
        ws.title = re.sub(r"[\\/*?:\[\]]", "_", title)[:31] or "Sheet1"
        ws.append(headers)
        for row in rows:
            ws.append(row)
        wb.save(meta["path"])
        meta["status"] = "ok"
        return meta
    except Exception as e:
        return {"status": "error", "error": str(e)}


@register_tool("generate_presentation")
def generate_presentation(title: str, slides_content: list) -> dict:
    """Generate a PowerPoint presentation (.pptx).

    Args:
        title: Main title of the presentation.
        slides_content: A list of dictionaries containing 'title' and 'content' for each slide.
    """
    try:
        meta = _save("pptx", title)
        prs = Presentation()

        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        slide.shapes.title.text = title
        slide.placeholders[1].text = "Generated by Kavach AI"

        bullet_slide_layout = prs.slide_layouts[1]
        for slide_data in slides_content:
            slide = prs.slides.add_slide(bullet_slide_layout)
            slide.shapes.title.text = slide_data.get("title", "")
            slide.shapes.placeholders[1].text_frame.text = slide_data.get("content", "")

        prs.save(meta["path"])
        meta["status"] = "ok"
        return meta
    except Exception as e:
        return {"status": "error", "error": str(e)}


@register_tool("generate_pdf_document")
def generate_pdf_document(title: str, content: str, author: str = "Kavach AI") -> dict:
    """Generate a formatted PDF document (.pdf).

    Args:
        title: Title of the document.
        content: The main body text of the document.
        author: Author of the document.
    """
    try:
        from fpdf import FPDF

        meta = _save("pdf", title)

        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Arial", "B", 16)
        pdf.cell(0, 10, title, ln=True, align="C")
        pdf.ln(10)

        pdf.set_font("Arial", "I", 12)
        pdf.cell(0, 10, f"Author: {author}", ln=True)
        pdf.ln(5)

        pdf.set_font("Arial", "", 11)
        # Clean unicode characters for FPDF's default Arial
        clean_content = content.encode("latin-1", "replace").decode("latin-1")
        # multi_cell automatically wraps text
        pdf.multi_cell(0, 6, clean_content)

        pdf.output(str(meta["path"]))
        meta["status"] = "ok"
        return meta
    except Exception as e:
        return {"status": "error", "error": str(e)}
