import re
import uuid
from html import unescape
from pathlib import Path

from docx import Document
from openpyxl import Workbook
from pptx import Presentation

from app.core.paths import OUTPUT_DIR
from app.tools.registry import register_tool


def _save(suffix: str, title: str) -> dict:
    """Build output path with UUID prefix and return metadata."""
    file_id = str(uuid.uuid4())
    safe_title = re.sub(r"[^A-Za-z0-9._-]+", "_", title).strip("._-")[:100] or "untitled"
    filename = f"{file_id}_{safe_title}.{suffix}"
    return {"file_id": file_id, "filename": filename, "path": OUTPUT_DIR / filename}


def _safe_excel_cell(value):
    if isinstance(value, str) and value.startswith(("=", "+", "-", "@")):
        return "'" + value
    return value


def _plain_document_text(content: str) -> str:
    """Remove model formatting tokens before writing prose documents."""
    content = re.sub(r"```[\w-]*\s*|```", "", content)
    content = re.sub(r"!?(?:\[([^\]]*)\]\([^)]*\))", r"\1", content)
    content = re.sub(r"(?m)^\s{0,3}#{1,6}\s+", "", content)
    content = re.sub(r"(\*\*|__|~~|`)", "", content)
    content = re.sub(r"<[^>]+>", "", content)
    return unescape(content).strip()


def _unicode_font() -> Path:
    candidates = (
        Path("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"),
        Path("C:/Windows/Fonts/arial.ttf"),
        Path("/System/Library/Fonts/Supplemental/Arial Unicode.ttf"),
    )
    if font := next((path for path in candidates if path.is_file()), None):
        return font
    raise RuntimeError("Unicode PDF font unavailable")


def _validate_pdf_text(font: Path, text: str) -> None:
    from fontTools.ttLib import TTFont

    shaping_ranges = ((0x0600, 0x06FF), (0x0900, 0x097F), (0x0C80, 0x0CFF))
    if any(start <= ord(char) <= end for char in text for start, end in shaping_ranges):
        raise ValueError("PDF script shaping is unavailable for Arabic, Devanagari, and Kannada")
    with TTFont(font, lazy=True) as loaded_font:
        supported = loaded_font.getBestCmap() or {}
    missing = sorted({ord(char) for char in text if ord(char) >= 32 and ord(char) not in supported})
    if missing:
        sample = ", ".join(f"U+{codepoint:04X}" for codepoint in missing[:5])
        raise ValueError(f"PDF font does not support requested characters: {sample}")


@register_tool("generate_word_document")
def generate_word_document(title: str, content: str, author: str = "Kavach AI") -> dict:
    """Generate a formatted Word document (.docx).

    Args:
        title: Title of the document.
        content: The main body text of the document.
        author: Author of the document.
    """
    try:
        meta = _save("docx", title)
        doc = Document()
        doc.add_heading(title, 0)
        doc.add_paragraph(f"Author: {author}")
        doc.add_paragraph(_plain_document_text(content))
        doc.save(meta["path"])
        meta["status"] = "ok"
        return meta
    except Exception as e:
        return {"status": "error", "error": str(e)}


@register_tool("generate_excel_sheet")
def generate_excel_sheet(title: str, headers: list, rows: list) -> dict:
    """Generate an Excel spreadsheet (.xlsx).

    Args:
        title: Title of the sheet.
        headers: A list of column headers.
        rows: A list of rows, where each row is a list of cell values.
    """
    try:
        meta = _save("xlsx", title)
        wb = Workbook()
        ws = wb.active
        ws.title = re.sub(r"[\\/*?:\[\]]", "_", title)[:31] or "Sheet1"
        ws.append([_safe_excel_cell(value) for value in headers])
        for row in rows:
            ws.append([_safe_excel_cell(value) for value in row])
        wb.save(meta["path"])
        meta["status"] = "ok"
        return meta
    except Exception as e:
        return {"status": "error", "error": str(e)}


@register_tool("generate_presentation")
def generate_presentation(title: str, slides_content: list) -> dict:
    """Generate a PowerPoint presentation (.pptx).

    Args:
        title: Main title of the presentation.
        slides_content: A list of dictionaries containing 'title' and 'content' for each slide.
    """
    try:
        meta = _save("pptx", title)
        prs = Presentation()

        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        slide.shapes.title.text = title
        slide.placeholders[1].text = "Generated by Kavach AI"

        bullet_slide_layout = prs.slide_layouts[1]
        for slide_data in slides_content:
            slide = prs.slides.add_slide(bullet_slide_layout)
            slide.shapes.title.text = slide_data.get("title", "")
            slide.shapes.placeholders[1].text_frame.text = slide_data.get("content", "")

        prs.save(meta["path"])
        meta["status"] = "ok"
        return meta
    except Exception as e:
        return {"status": "error", "error": str(e)}


@register_tool("generate_pdf_document")
def generate_pdf_document(title: str, content: str, author: str = "Kavach AI") -> dict:
    """Generate a formatted PDF document (.pdf).

    Args:
        title: Title of the document.
        content: The main body text of the document.
        author: Author of the document.
    """
    try:
        from fpdf import FPDF

        meta = _save("pdf", title)

        pdf = FPDF()
        pdf.add_page()
        font = _unicode_font()
        content = _plain_document_text(content)
        _validate_pdf_text(font, f"{title}\nAuthor: {author}\n{content}")
        pdf.add_font("KavachUnicode", fname=str(font))
        pdf.set_font("KavachUnicode", size=16)
        pdf.cell(0, 10, title, ln=True, align="C")
        pdf.ln(10)

        pdf.set_font("KavachUnicode", size=12)
        pdf.cell(0, 10, f"Author: {author}", ln=True)
        pdf.ln(5)

        pdf.set_font("KavachUnicode", size=11)
        pdf.multi_cell(0, 6, content)

        pdf.output(str(meta["path"]))
        meta["status"] = "ok"
        return meta
    except Exception as e:
        return {"status": "error", "error": str(e)}
