"use client";

import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { FileText, FileCode2, Image as ImageIcon, File, User, Bot, Download, X } from "lucide-react";

export interface Artifact {
  id: string;
  name: string;
  type: string;
  origin: "user" | "agent";
  content?: string;
  url?: string;
}

interface ChatArtifactsModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  artifacts: Artifact[];
}

export function ChatArtifactsModal({ open, onOpenChange, artifacts }: ChatArtifactsModalProps) {
  const [selectedId, setSelectedId] = useState<string | null>(null);

  const getIcon = (type: string) => {
    const t = type.toLowerCase();
    if (['png', 'jpg', 'jpeg', 'gif', 'svg', 'webp'].includes(t)) return <ImageIcon className="w-5 h-5 text-blue-500" />;
    if (['py', 'js', 'ts', 'jsx', 'tsx', 'json', 'html', 'css'].includes(t)) return <FileCode2 className="w-5 h-5 text-emerald-500" />;
    if (['pdf', 'docx', 'txt', 'md', 'csv', 'xlsx'].includes(t)) return <FileText className="w-5 h-5 text-amber-500" />;
    return <File className="w-5 h-5 text-gray-500" />;
  };

  const selectedArtifact = artifacts.find(a => a.id === selectedId) || artifacts[0];

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="!max-w-[100vw] sm:!max-w-[100vw] !w-screen !h-screen flex flex-col p-0 gap-0 border-none rounded-none bg-background">
        <DialogHeader className="p-4 border-b border-border shrink-0 flex flex-row items-center justify-between">
          <div>
            <DialogTitle className="text-xl flex items-center gap-2">
              <FileCode2 className="w-6 h-6 text-emerald-500" />
              Conversation Artifacts
            </DialogTitle>
            <DialogDescription className="text-muted-foreground mt-1 text-sm">
              View all files uploaded by you and generated by Kavach AI in this session.
            </DialogDescription>
          </div>
          <button 
            onClick={() => onOpenChange(false)}
            className="p-2 hover:bg-muted rounded-full transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </DialogHeader>

        <div className="flex flex-1 overflow-hidden">
          {/* Left Sidebar - List */}
          <div className="w-80 border-r border-border bg-sidebar flex flex-col overflow-y-auto">
            <div className="p-4 font-semibold text-xs uppercase tracking-wider text-muted-foreground">
              Files & Documents ({artifacts.length})
            </div>
            <div className="flex flex-col gap-1 px-3 pb-4">
              {artifacts.map(a => (
                <button
                  key={a.id}
                  onClick={() => setSelectedId(a.id)}
                  className={`flex flex-col gap-1 p-3 rounded-lg text-left transition-colors border ${
                    (selectedArtifact?.id === a.id)
                      ? "bg-primary/10 border-primary/30"
                      : "bg-card border-border hover:border-primary/50"
                  }`}
                >
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex items-center gap-2 overflow-hidden">
                      {getIcon(a.type)}
                      <span className="font-medium text-sm truncate">{a.name}</span>
                    </div>
                  </div>
                  <div className="flex items-center gap-1.5 mt-1">
                    {a.origin === "user" ? (
                      <User className="w-3.5 h-3.5 text-blue-500" />
                    ) : (
                      <Bot className="w-3.5 h-3.5 text-emerald-500" />
                    )}
                    <span className="text-xs text-muted-foreground capitalize">
                      {a.origin} • {a.type.toUpperCase()}
                    </span>
                  </div>
                </button>
              ))}
              {artifacts.length === 0 && (
                <div className="text-sm text-muted-foreground italic p-2 text-center">
                  No artifacts found in this conversation.
                </div>
              )}
            </div>
          </div>

          {/* Right Area - Preview */}
          <div className="flex-1 bg-background flex flex-col overflow-hidden relative">
            {selectedArtifact ? (
              <div className="h-full flex flex-col">
                <div className="h-14 border-b border-border flex items-center justify-between px-6 shrink-0 bg-card">
                  <div className="flex items-center gap-3">
                    {getIcon(selectedArtifact.type)}
                    <span className="font-semibold">{selectedArtifact.name}</span>
                  </div>
                  <button className="flex items-center gap-2 px-3 py-1.5 bg-primary text-primary-foreground rounded-md text-sm font-medium hover:bg-primary/90 transition-colors">
                    <Download className="w-4 h-4" />
                    Download
                  </button>
                </div>
                <div className="flex-1 overflow-auto p-8 bg-muted/30 flex items-center justify-center">
                  {selectedArtifact.origin === "user" && ['png', 'jpg', 'jpeg', 'webp'].includes(selectedArtifact.type.toLowerCase()) ? (
                    <div className="max-w-3xl max-h-full border border-border shadow-sm rounded-lg overflow-hidden bg-white">
                      <div className="p-8 flex flex-col items-center justify-center text-center gap-4 text-muted-foreground">
                        <ImageIcon className="w-16 h-16 opacity-50" />
                        <p>Image preview placeholder.<br/>(Preview rendering not currently wired to file blobs.)</p>
                      </div>
                    </div>
                  ) : (
                    <div className="w-full max-w-4xl bg-card border border-border shadow-sm rounded-lg min-h-[60vh] p-8 font-mono text-sm text-foreground overflow-auto">
                      {selectedArtifact.content ? (
                        <pre className="whitespace-pre-wrap">{selectedArtifact.content}</pre>
                      ) : (
                        <div className="h-full flex flex-col items-center justify-center text-muted-foreground gap-4 opacity-70">
                          {getIcon(selectedArtifact.type)}
                          <p>Preview not available for this file type.</p>
                          <p className="text-xs">Click Download to view.</p>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              </div>
            ) : (
              <div className="h-full flex flex-col items-center justify-center text-muted-foreground">
                <FileCode2 className="w-16 h-16 mb-4 opacity-20" />
                <p>Select an artifact from the list to preview.</p>
              </div>
            )}
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
