"use client";

import { useEffect, useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { FileText, FileCode2, Image as ImageIcon, File, User, Bot, Download } from "lucide-react";

export interface Artifact {
  id: string;
  name: string;
  type: string;
  origin: "user" | "agent";
  content?: string;
  url?: string;
}

interface ChatArtifactsModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  artifacts: Artifact[];
}

interface ArtifactPreview {
  preview_kind: "text" | "image" | "unsupported";
  text?: string;
  truncated?: boolean;
  image_url?: string;
}

export function ChatArtifactsModal({ open, onOpenChange, artifacts }: ChatArtifactsModalProps) {
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [preview, setPreview] = useState<ArtifactPreview | null>(null);
  const [isLoadingPreview, setIsLoadingPreview] = useState(false);

  const getIcon = (type: string) => {
    const t = type.toLowerCase();
    if (['png', 'jpg', 'jpeg', 'gif', 'svg', 'webp'].includes(t)) return <ImageIcon className="w-5 h-5 text-blue-500" />;
    if (['py', 'js', 'ts', 'jsx', 'tsx', 'json', 'html', 'css'].includes(t)) return <FileCode2 className="w-5 h-5 text-emerald-500" />;
    if (['pdf', 'docx', 'txt', 'md', 'csv', 'xlsx'].includes(t)) return <FileText className="w-5 h-5 text-amber-500" />;
    return <File className="w-5 h-5 text-gray-500" />;
  };

  const selectedArtifact = artifacts.find(a => a.id === selectedId) || artifacts[0];
  const apiBase = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
  const downloadUrl = selectedArtifact ? `${apiBase}/api/files/download/${selectedArtifact.id}` : "";

  useEffect(() => {
    if (!open || !selectedArtifact || selectedArtifact.type.toLowerCase() === "pdf") return;
    const controller = new AbortController();
    setIsLoadingPreview(true);
    setPreview(null);
    fetch(`${apiBase}/api/files/${selectedArtifact.id}/preview`, { signal: controller.signal })
      .then((response) => response.ok ? response.json() : Promise.reject(new Error("Preview unavailable")))
      .then((data: ArtifactPreview) => setPreview(data))
      .catch(() => { if (!controller.signal.aborted) setPreview({ preview_kind: "unsupported" }); })
      .finally(() => { if (!controller.signal.aborted) setIsLoadingPreview(false); });
    return () => controller.abort();
  }, [apiBase, open, selectedArtifact]);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="!max-w-7xl !w-[95vw] h-[85vh] flex flex-col p-0 gap-0 border border-border rounded-xl bg-background overflow-hidden shadow-2xl">
        <DialogHeader className="p-4 border-b border-border shrink-0 flex flex-row items-center justify-between bg-card/50">
          <div>
            <DialogTitle className="text-xl flex items-center gap-2">
              <FileCode2 className="w-6 h-6 text-emerald-500" />
              Conversation Artifacts
            </DialogTitle>
            <DialogDescription className="text-muted-foreground mt-1 text-sm">
              View all files uploaded by you and generated by Kavach AI in this session.
            </DialogDescription>
          </div>
        </DialogHeader>

        <div className="flex flex-1 overflow-hidden">
          {/* Left Sidebar - List */}
          <div className="w-80 border-r border-border bg-sidebar flex flex-col overflow-y-auto">
            <div className="p-4 font-semibold text-xs uppercase tracking-wider text-muted-foreground">
              Files & Documents ({artifacts.length})
            </div>
            <div className="flex flex-col gap-1 px-3 pb-4">
              {artifacts.map(a => (
                <button
                  key={a.id}
                  onClick={() => setSelectedId(a.id)}
                  className={`flex flex-col gap-1 p-3 rounded-lg text-left transition-colors border ${
                    (selectedArtifact?.id === a.id)
                      ? "bg-primary/10 border-primary/30"
                      : "bg-card border-border hover:border-primary/50"
                  }`}
                >
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex items-center gap-2 overflow-hidden">
                      {getIcon(a.type)}
                      <span className="font-medium text-sm truncate">{a.name}</span>
                    </div>
                  </div>
                  <div className="flex items-center gap-1.5 mt-1">
                    {a.origin === "user" ? (
                      <User className="w-3.5 h-3.5 text-blue-500" />
                    ) : (
                      <Bot className="w-3.5 h-3.5 text-emerald-500" />
                    )}
                    <span className="text-xs text-muted-foreground capitalize">
                      {a.origin} • {a.type.toUpperCase()}
                    </span>
                  </div>
                </button>
              ))}
              {artifacts.length === 0 && (
                <div className="text-sm text-muted-foreground italic p-2 text-center">
                  No artifacts found in this conversation.
                </div>
              )}
            </div>
          </div>

          {/* Right Area - Preview */}
          <div className="flex-1 bg-background flex flex-col overflow-hidden relative">
            {selectedArtifact ? (
              <div className="h-full flex flex-col">
                <div className="h-14 border-b border-border flex items-center justify-between px-6 shrink-0 bg-card">
                  <div className="flex items-center gap-3">
                    {getIcon(selectedArtifact.type)}
                    <span className="font-semibold">{selectedArtifact.name}</span>
                  </div>
                  <a href={downloadUrl} download className="flex items-center gap-2 px-3 py-1.5 bg-primary text-primary-foreground rounded-md text-sm font-medium hover:bg-primary/90 transition-colors">
                    <Download className="w-4 h-4" />
                    Download
                  </a>
                </div>
                <div className="flex-1 overflow-auto p-8 bg-muted/30 flex items-center justify-center">
                  {selectedArtifact.name.toLowerCase().endsWith('.pdf') || selectedArtifact.type.toLowerCase() === 'pdf' ? (
                    <div className="w-full h-full max-w-5xl bg-card border border-border shadow-sm rounded-lg overflow-hidden">
                      <iframe 
                        src={`${downloadUrl}#toolbar=0&navpanes=0`} 
                        className="w-full h-full"
                        title={selectedArtifact.name}
                      />
                    </div>
                  ) : preview?.preview_kind === "image" ? (
                    <>
                      {/* Browser-served private uploads cannot use Next image optimization. */}
                      {/* eslint-disable-next-line @next/next/no-img-element */}
                      <img src={`${apiBase}${preview.image_url}`} alt={selectedArtifact.name} className="max-h-full max-w-full rounded-lg border border-border object-contain" />
                    </>
                  ) : preview?.preview_kind === "text" ? (
                    <div className="w-full max-w-4xl bg-card border border-border shadow-sm rounded-lg min-h-[60vh] p-8 font-mono text-sm text-foreground overflow-auto">
                      <pre className="whitespace-pre-wrap break-words">{preview.text}</pre>
                      {preview.truncated && <p className="mt-4 text-xs text-muted-foreground">Preview truncated. Download file to view all content.</p>}
                    </div>
                  ) : (
                    <div className="w-full max-w-4xl bg-card border border-border shadow-sm rounded-lg min-h-[60vh] p-8 font-mono text-sm text-foreground overflow-auto">
                      <div className="h-full flex flex-col items-center justify-center text-muted-foreground gap-4 opacity-70">
                        {getIcon(selectedArtifact.type)}
                        <p>{isLoadingPreview ? "Loading preview..." : "Preview not available for this file type."}</p>
                        {!isLoadingPreview && <p className="text-xs">Download file to view it.</p>}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            ) : (
              <div className="h-full flex flex-col items-center justify-center text-muted-foreground">
                <FileCode2 className="w-16 h-16 mb-4 opacity-20" />
                <p>Select an artifact from the list to preview.</p>
              </div>
            )}
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
