"""
Kavach AI — ReAct Agent Executor
Dispatches individual step execution requests to the Tool Registry.
"""

from typing import Dict, Any
from loguru import logger
from app.tools.registry import execute_tool, _TOOL_REGISTRY
from app.tools.code_execute import execute_python_code

# Import tool modules so their @register_tool decorators fire at import time
import app.tools.file_read       # noqa: F401
import app.tools.file_write      # noqa: F401
import app.tools.doc_generate    # noqa: F401
import app.tools.ocr_extract     # noqa: F401
import app.tools.image_analyze   # noqa: F401
import app.rag.knowledge_search  # noqa: F401

# Map planner conceptual tool names to registry tool names
TOOL_ALIASES = {
    "knowledge_search": "search_knowledge_base",
    "doc_generate": "generate_word_document",
    "ocr_extract": "extract_text_from_image",
    "image_analyze": "analyze_engineering_diagram",
}


class AgentExecutor:
    """Dispatches tool execution calls based on step recommendations."""

    async def execute_step(
        self,
        step_number: int,
        tool_name: str,
        tool_input: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Executes a specified tool with given input arguments.
        Routes to the Tool Registry with alias resolution and parameter adaptation.
        """
        # Resolve aliases
        effective_tool = TOOL_ALIASES.get(tool_name, tool_name)
        logger.info(f"Executing step #{step_number} with tool: {effective_tool} (original: {tool_name})")

        try:
            # Special case: code execution uses its own subprocess sandbox
            if effective_tool == "code_execute":
                code = tool_input.get("code", "print('Kavach AI sandbox verification successful')")
                res = await execute_python_code(code=code)
                return {
                    "tool": "code_execute",
                    "success": res.get("success", False),
                    "output": res.get("output", ""),
                    "raw": res
                }

            # Map arguments according to the specific registered tool
            kwargs = {}
            if effective_tool == "search_knowledge_base":
                query = tool_input.get("query") or tool_input.get("task") or tool_input.get("step_title", "")
                kwargs = {"query": query}

            elif effective_tool == "generate_word_document":
                title = tool_input.get("title") or tool_input.get("step_title") or "MRPL_Approval_Note"
                content = tool_input.get("content") or tool_input.get("task", "Generated by Kavach AI Workbench.")
                author = tool_input.get("author", "Kavach AI")
                kwargs = {"title": title, "content": content, "author": author}

            elif effective_tool == "generate_excel_sheet":
                title = tool_input.get("title") or "MRPL_Data"
                headers = tool_input.get("headers", ["Item", "Value", "Status"])
                rows = tool_input.get("rows", [["Inspection", "Passed", "Normal"]])
                kwargs = {"title": title, "headers": headers, "rows": rows}

            elif effective_tool == "generate_presentation":
                title = tool_input.get("title") or "MRPL_Summary"
                slides_content = tool_input.get("slides_content", [{"title": "Overview", "content": "Kavach AI Summary"}])
                kwargs = {"title": title, "slides_content": slides_content}

            elif effective_tool == "file_read":
                filepath = tool_input.get("filepath", "")
                kwargs = {"filepath": filepath}

            elif effective_tool == "file_write":
                filepath = tool_input.get("filepath", "note.txt")
                content = tool_input.get("content", "")
                kwargs = {"filepath": filepath, "content": content}

            elif effective_tool == "extract_text_from_image":
                filepath = tool_input.get("filepath") or tool_input.get("image_path", "")
                kwargs = {"filepath": filepath}

            elif effective_tool == "analyze_engineering_diagram":
                filepath = tool_input.get("filepath") or tool_input.get("image_path", "")
                query = tool_input.get("query") or tool_input.get("task", "")
                kwargs = {"filepath": filepath, "query": query}

            else:
                kwargs = tool_input

            # Execute tool if found in registry
            if effective_tool in _TOOL_REGISTRY:
                result = await execute_tool(effective_tool, kwargs)
                res_str = str(result)
                file_id = None
                # If a document was generated, extract filename as deliverable ID
                if "Successfully generated" in res_str and ":" in res_str:
                    file_id = res_str.split(":")[-1].strip()

                return {
                    "tool": effective_tool,
                    "success": not res_str.startswith("Error"),
                    "output": res_str,
                    "file_id": file_id
                }

            # Default: reasoning step with no external tool call
            return {
                "tool": tool_name or "none",
                "success": True,
                "output": f"Step #{step_number} reasoning and execution completed."
            }

        except Exception as e:
            logger.error(f"Error in step #{step_number} tool execution ({effective_tool}): {e}")
            return {
                "tool": effective_tool,
                "success": False,
                "output": f"Error executing tool {effective_tool}: {str(e)}"
            }


executor = AgentExecutor()
